/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br> </br> <b>Integrations (SDKs, Tools) links:</b> </br> <a href=\"https://deploy.equinix.com/labs/fabric-java\\\">Fabric Java SDK</a> </br> <a href=\"https://deploy.equinix.com/labs/equinix-sdk-go\\\">Fabric Go SDK</a> </br> <a href=\"https://deploy.equinix.com/labs/terraform-provider-equinix\\\">Equinix Terraform Provider</a> </br> <a href=\"https://deploy.equinix.com/labs/terraform-equinix-fabric\\\">Fabric Terraform Modules</a> </br> <a href=\"https://deploy.equinix.com/labs/pulumi-provider-equinix/\">Equinix Pulumi Provider</a> </br>
 *
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// AccessPointType : Access point type
type AccessPointType string

// List of AccessPointType
const (
	VD_AccessPointType             AccessPointType = "VD"
	VG_AccessPointType             AccessPointType = "VG"
	SP_AccessPointType             AccessPointType = "SP"
	IGW_AccessPointType            AccessPointType = "IGW"
	COLO_AccessPointType           AccessPointType = "COLO"
	SUBNET_AccessPointType         AccessPointType = "SUBNET"
	CLOUD_ROUTER_AccessPointType   AccessPointType = "CLOUD_ROUTER"
	NETWORK_AccessPointType        AccessPointType = "NETWORK"
	METAL_NETWORK_AccessPointType  AccessPointType = "METAL_NETWORK"
	VPIC_INTERFACE_AccessPointType AccessPointType = "VPIC_INTERFACE"
)
