on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Verify Patches
      run: make patch
    - name: Generate
      run: |
        make clean gen mod fmt patch-post docs move-other test
        # Expect all changes to be accounted for
        git diff
        ! git status --porcelain | grep .
